name: "Update changelog on PR merge"
on:
  workflow_call:

jobs:
  update_changelog:
    if: |
      github.event.pull_request.merged == true && 
      !startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Update CHANGELOG.md'
        run: |
          UPDATE_TITLE=$(echo "${UPDATE_TITLE_ENV}" | sed -e 's/\\/\\\\/g' -e 's/$/\\&/g')
          UPDATE_BODY=$(echo "${UPDATE_BODY_ENV}" | sed -e 's/^/&  /g' -e 's/\\/\\\\/g' -e 's/$/\\&/g')
          sed -i "/## \[Unreleased\]/a\\\n- ### ${UPDATE_TITLE}n${UPDATE_BODY}n---" CHANGELOG.md
        env:
          UPDATE_TITLE_ENV: '${{ github.event.pull_request.title }}'
          UPDATE_BODY_ENV: '${{ github.event.pull_request.body }}'
      - name: Amend the last commit
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "Version Update"
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"
